### PR TITLE
Revert Bad Example Edits

### LINKED ISSUE #32: The example/counter.rs file doesn't work.
When running `cargo run --example counter --target=aarch64-apple-darwin` as recommended in the README.md for this repository, an error is reported because the `rpc_url` variable is set to the empty string.

Even with a `.env` file created according to the specifications in the README.md file, the string remains empty. After brief inspection of the code, it looks like a lot of the code is commented out.

### PR DESCRIPTION
**Pull request by rauljordan**
Closes #32

### CODE REVIEW

**Review by joshuacolvin0 — APPROVED** [review]
LGTM

File: examples/counter.rs [hunk 1]
```diff
@@ -17,23 +17,21 @@ use std::str::FromStr;
...
 /// Stylus RPC endpoint url.
-const RPC_URL: &str = "";
+const RPC_URL: &str = "RPC_URL";
 
 /// Deployed pragram address.
-const STYLUS_PROGRAM_ADDRESS: &str = "";
+const STYLUS_PROGRAM_ADDRESS: &str = "STYLUS_PROGRAM_ADDRESS";
 
 #[tokio::main]
 async fn main() -> eyre::Result<()> {
```
Comment (eljobe) [inline examples/counter.rs:29]: This doesn't completely fix it.
You also need to use the dotenv crate https://crates.io/crates/dotenv to actually read the .env file with a call at the top of main to:
dotenv().ok()

**Review by eljobe — CHANGES_REQUESTED** [review]
